---
- name: Install nginx
  yum: name=nginx state=present

- name: Copy nginx configuration for wordpress
  template: src=default.conf dest=/etc/nginx/conf.d/{{ item.value.server_hostname }}.conf
  notify: restart nginx
  with_dict: "{{blogs}}"

- name: insert firewalld rule for nginx
  firewalld: port={{ nginx_port }}/tcp permanent=true state=enabled immediate=yes

- name: nginx service state
  service: name=nginx state=started enabled=yes
